server:
  port: 8888
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.134:3307/project?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123
  redis:
    host: 192.168.0.134
    database: 0
    port: 6380
    password: 123

# 日志
logging:
  config: classpath:conf/logback-spring-prod.xml
