spring:
  profiles:
    active: prod
  data:
    redis:
      repositories:
        enabled: false
  ## 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    ## 连接超时时间（毫秒）
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        # 连接池阻塞等待时间（负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中最小空闲连接
        min-idle: 0
  cache:
    type: redis
  mail:
    host: smtp.163.com
    default-encoding: UTF-8
    username: 你的邮箱地址
    password: 你的授权码

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mybatis/*/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.learn.project.project.entity
  global-config:
    db-config:
      id-type: AUTO
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      logic-delete-field: flag

  configuration:
    # 配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 配置JdbcTypeForNull, oracle数据库必须配置
    # jdbc-type-for-null: 'null'
