server:
  port: 8888
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.0.134:3306/project?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123
  redis:
    host: 192.168.0.134
    port: 6379
    password: 123

# 日志
logging:
  config: classpath:conf/logback-spring-dev.xml

