version: '3'

networks:
  server:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '${DOCKER_BRIDGE_SUBNET:-172.28.0.0/16}'
          gateway: '${DOCKER_BRIDGE_GATEWAY:-172.28.0.1}'

services:
  mysql:
    # https://hub.docker.com/_/mysql/tags
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - '${DATA_DIR:-./}/volumes/mysql/data:/var/lib/mysql'
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    networks:
      server:
        ipv4_address: ${REDIS_NETWORK_ADDRESS:-172.28.0.3}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppass" ]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    # https://hub.docker.com/_/redis/tags
    image: redis:7.2.4-alpine
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - "${DATA_DIR:-./}/volumes/redis/data:/data"
      - "${DATA_DIR:-./}/volumes/redis/config/redis.conf:/usr/local/redis/config/redis.conf"
    environment:
      TZ: Asia/Shanghai
    restart: always
    sysctls:
      net.core.somaxconn: 1024
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    networks:
      server:
        ipv4_address: ${REDIS_NETWORK_ADDRESS:-172.28.0.6}

  minio:
    # https://hub.docker.com/r/minio/minio/tags
    image: minio/minio:RELEASE.2024-04-06T05-26-02Z.fips
    ports:
      - "${MINIO_PORT}:9000"
      - "9090:9090"
    container_name: minio
    volumes:
      - "${DATA_DIR:-./}/volumes/minio/data:/data"
      - "${DATA_DIR:-./}/volumes/minio/config:/root/.minio"
    environment:
      MINIO_ROOT_USER: "${MINIO_ACCESS_KEY}"
      MINIO_ROOT_PASSWORD: "${MINIO_SECRET_KEY}"
    restart: always
    command: minio server /data --console-address ':9090'
    networks:
      server:
        ipv4_address: ${MINIO_NETWORK_ADDRESS:-172.28.0.9}
